server:
  context-path: /
  port: 8002
#断路器请求超时时间设定
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000 
    
#开启断路器
feign:
  hystrix:
    enabled: true
  compression:
    request:
      min-request-size: 2048  
      mime-types:
        - text/xml, application/xml, application/json
      enabled: true
    respoonse: 
      enabled: true
      
spring: 
  http: 
    encoding:
      charset: UTF-8 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL  
  ##DATASOURCE CONFIGURATION -- see druid.yml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.31:3306/transport?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root  
    druid: 
      ##下面为连接池的补充设置，应用到上面所有数据源中
      #初始化大小，最小，最大
      initialSize: 50
      minIdle: 10
      maxIdle: 10
      maxActive: 300
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      filters: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true  
      aop-patterns: bhz.springboot.service.*
      StatViewServlet: 
        enabled: true
        urlPattern: /druid/*
        resetEnable:
        loginUsername: bhz
        loginPassword:  bhz
        allow: 127.0.0.1
        deny:  

mybatis:
    type-aliases-package: bhz.order
    mapper-locations: classpath:bhz/transport/mapping/*.xml

logging:
    level:
        tk.mybatis: TRACE  
        
        
pagehelper: 
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


dubbo:
  application:
    id: core-transport
    name: core-transport
    qos-prot: 22222
    qos-enable: true 
  scan:
    basePackages: bhz.transport.service,bhz.transport.service.*
  protocol:
    id: dubbo
    name: dubbo
    prot: 12345
  registry:
    id: core-transport-registry
    address: zookeeper://192.168.1.111:2181?backup=192.168.1.112:2181,192.168.1.113:2181        

management:
  port: 8012 
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
      
endpoints:
  dubbo:
    enabled: true    
    
    
    